config/routes.rb
Rails.application.routes.draw do
  get 'doctors/index'
  get 'patients/index'
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  resources :patients
  resources :doctors
  resources :book_appointments, only: [:index]
  resources :appointments do
    get 'booking'
    get 'accept'
    get 'reject'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
# frozen_string_literal: true

class Appointment < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient

  enum status: %i[pending accepted rejected]
  ACCEPTED = 'Accepted'
  REJECTED = 'Rejected'
  PENDING = 'Pending'
  validate :start_time_cannot_be_in_the_past
  validate :time_validate
  validate :start_time_less_then_end_time
  validate :validate_doctor_time

  private

  def validate_doctor_time
    doctor_appointments = User.find_by(id: doctor_id).appointments.where(status: 'accepted')
    doctor_appointments. each do |appointment|
      next unless (start_time..end_time).overlaps?(appointment.start_time..appointment.end_time)
      
      errors.add(:start_time, '^doctor unavailable on this time')
    end
  end

  def start_time_less_then_end_time
    return if start_time < end_time

    errors.add(:start_time, '^end time should be greater then start time')
  end

  def start_time_cannot_be_in_the_past
    return if start_time > Time.now

    errors.add(:start_time, 'should be greater then current time')
  end

  def time_validate
    start_time_validate(start_time, doctor.available_start_time)
    end_time_validate(end_time, doctor.available_end_time)
  end

  def start_time_validate(patient_start_time, doctor_time)
    return if time_only(patient_start_time) >= time_only(doctor_time)

    error_message('start_time')
  end

  def end_time_validate(patient_end_time, doctor_time)
    return if time_only(patient_end_time) <= time_only(doctor_time)

    error_message('end_time')
  end

  def error_message(start_end_time)
    errors.add(start_end_time.to_sym, "^your #{start_end_time} is not suitable for Doctor")
  end

  def time_only(time)
    time.strftime(GlobalConstants::TIME_FORMATE)
  end
end

app/models/doctor.rb
# frozen_string_literal: true

class Doctor < User
  has_many :patients
  has_many :appointments
  SPECIALIST_TYPE = {
    Dermatologists: 'Dermatologists',
    Endocrinologists: 'Endocrinologists',
    Gastroenterologists: 'Gastroenterologists',
    Internists: 'Internists'
  }.freeze
end

app/models/patient.rb
# frozen_string_literal: true

class Patient < User
  has_many :doctors
  has_many :appointments
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, :last_name, presence: true
  USER_TYPE = { doctor: 'Doctor', patient: 'Patient' }.freeze

  def self.doctor?(current_user)
    current_user.type == User::USER_TYPE[:doctor]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/appointments_controller.rb
# frozen_string_literal: true

class AppointmentsController < ApplicationController
  before_action :validate_user_patient, only: [:create]
  before_action :validate_user_doctor, only: %i[reject accept]
  def booking
    @booking = Appointment.new
  end

  def create
    @booking = current_user.appointments.new(booking_params)
    @booking.doctor_id = params.dig(:doctor_id).to_i
    change_date
    @booking.save!
    redirect_to patients_index_path
  rescue Exception => e
    params[:appointment_id] = @booking.doctor_id
    render 'booking'
  end

  def reject
    change_status(2)
  end

  def accept
    change_status(1)
  end

  private

  def change_date
    date = params.dig(:appointment, :date).to_date
    @booking.start_time = @booking.start_time.change(year: date&.year, month: date&.month, day: date.day)
    @booking.end_time = @booking.end_time.change(year: date&.year, month: date&.month, day: date.day)
  end

  def change_status(status)
    appointment = Appointment.find_by(id: params.dig(:appointment_id))
    unless appointment.update(status: status)
      flash[:error] = 'you already have an appointment on this time'
    end
    redirect_to doctors_index_path
  end

  def booking_params
    params.require(:appointment).permit(
      :start_time, :end_time
    )
  end

  def validate_user_patient
    return unless User.doctor?(current_user)

    redirect_to doctors_index_path
  end

  def validate_user_doctor
    return if User.doctor?(current_user)

    redirect_to patients_index_path
  end
end

app/controllers/book_appointments_controller.rb
class BookAppointmentsController < ApplicationController
  def index
    @doctors = Doctor.all
  end
end

app/controllers/doctors_controller.rb
# frozen_string_literal: true

class DoctorsController < ApplicationController
  before_action :validate_user
  def index
    @appointments = current_user.appointments
  end

  private

  def validate_user
    return if User.doctor?(current_user)

    redirect_to patients_index_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user.type == User::USER_TYPE[:doctor]
      redirect_to doctors_index_path
    else
      redirect_to patients_index_path
    end
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :validate_user
  def index
    @appointments = current_user.appointments
  end

  private
  
  def validate_user
    return unless User.doctor?(current_user)

    redirect_to doctors_index_path
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  before_action :configure_permitted_parameters, only: [:update]

  def new
    @user = User.new
    super
  end

  def update
    super
  end

  def create
    @user = User.new(user_params)
    @user.type = add_type
    add_available_time if doctor?
    @user.save!
    sign_in(@user)
    redirect_to root_path
  rescue Exception => e
    render 'new'
  end

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(
      :account_update,
      keys: %i[first_name last_name specialist available_start_time available_end_time]
    )
  end
  
  def add_available_time
    @user.available_start_time = add_time(7)
    @user.available_end_time = add_time(17)
  end

  def add_time(time)
    Time.now.utc.change(hour: time)
  end

  def doctor?
    params.dig(:role) == '0'
  end

  def add_type
    doctor? ? User::USER_TYPE[:doctor] : User::USER_TYPE[:patient]
  end

  def user_params
    params.require(:user).permit(
      :email, :first_name, :last_name,
      :password,
      :password_confirmation,
      :available_start_time,
      :available_end_time
    )
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def create
    resource = User.find_by(email: params.dig(:user, :email))
    if resource.present? && resource.valid_password?(params.dig(:user, :password))
      sign_in(resource)
      redirect_to root_path
    else
      super
    end
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
# frozen_string_literal: true

module AppointmentsHelper
  def doctor_id
    new_appointment? ? params.dig(:appointment_id) : @booking.doctor_id
  end

  def new_appointment?
    @booking.new_record?
  end
end

app/helpers/doctors_helper.rb
# frozen_string_literal: true

module DoctorsHelper
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
  
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  def status(appointment)
    if appointment.pending?
      Appointment::PENDING
    elsif appointment.accepted?
      Appointment::ACCEPTED
    else
      Appointment::REJECTED
    end
  end
end

app/views/appointments/booking.html.erb
<%= render "devise/shared/error_messages", resource: @booking %>
<%= form_for @booking, url: appointments_path do |f| %> 
  <%= hidden_field_tag :doctor_id, doctor_id  %>
  <div>
    <%= f.label :date %><br>
    <%= f.date_field :date, value: Date.today %><br />
  </div>

  <div>
    <%= f.label :start_time %><br>
    <%= f.time_select :start_time, value: Time.current %><br />
  </div>
   
  <div>
    <%= f.label :end_time %><br>
    <%= f.time_select :end_time, value: Time.current %><br />
  </div>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<br /><%= link_to "Back", book_appointments_path %><br /><br /><br />

app/views/book_appointments/index.html.erb
<table id='customers'>
  <tr>
    <th>Doctors Name</th>
    <th>Avalable Time</th>
    <th>Specialist</th>
    <th>Select Doctor</th>
  </tr>
  <% @doctors.each do |doctor| %>
    <tr>
      <td>
        <%= doctor&.first_name %>
      </td>
      <td>
        <%= doctor&.available_start_time.strftime(GlobalConstants::TIME_FORMATE) %> -
        <%= doctor&.available_end_time.strftime(GlobalConstants::TIME_FORMATE) %>
      </td>
      <td>
        <%= doctor&.specialist %>
      </td>
      <td>
        <%= link_to "Book Appointment", appointment_booking_path(doctor.id) %><br />
      </td>
    </tr>
  <% end %>
</table>

<br /><%= link_to "Back", patients_index_path %><br /><br /><br />

app/views/doctors/index.html.erb
<h2>welcome <%= current_user.first_name %></h2> <br />
<%= 'please complete profile your' if current_user.specialist.blank? %> <br /> 
<%= link_to "Edit profile", edit_user_registration_path %><br />
<h3>your appointments</h3>
<table id='customers'>
  <tr>
    <th>Patients Name</th>
    <th>date time</th>
    <th>Specialist</th>
  </tr>
  <% @appointments.each do |appointment| %>
    <tr>
      <td>
      <%= appointment&.patient.first_name %>
      </td>
      <td>
        <%= appointment&.start_time.strftime(GlobalConstants::DATE_FORMATE) %> : 
        <%= appointment&.start_time.strftime(GlobalConstants::TIME_FORMATE) %> -
        <%= appointment&.end_time.strftime(GlobalConstants::TIME_FORMATE) %>
      </td>
      <td>
      <% if appointment.status == 'pending' %>
        <%= link_to 'accept', appointment_accept_path(appointment)  %>
        <%= link_to 'reject', appointment_reject_path(appointment)  %>
      <% else %>
        <%= status(appointment) %>
      <% end %>
      </td>
    </tr>
  <% end %>
</table>
<br />

app/views/home/index.html.erb
done

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MvpForDoctor</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%- flash.each do |name, msg| -%>
      <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
    <%- end -%>
    <%= yield %>
    <br />
    <br />
    <br />
    <% if current_user.present?%>
      <br />
      <%= button_to "Sign out", destroy_user_session_path, method: 'delete' %><br />
    <% end %>
  </body>
</html>

app/views/patients/index.html.erb
<h1>welcome <%= current_user.first_name %><br /></h1>
<h2>your appointments</h2>
<table id='customers'>
  <tr>
    <th>Doctors Name</th>
    <th>date time</th>
    <th>Specialist</th>
    <th>Stutus</th>
  </tr>
  <% @appointments.each do |appointment| %>
    <tr>
      <td>
        <%= appointment&.doctor.first_name %>
      </td>
      <td>
        <%= appointment&.start_time.strftime(GlobalConstants::DATE_FORMATE) %> : 
        <%= appointment&.start_time.strftime(GlobalConstants::TIME_FORMATE) %> -
        <%= appointment&.end_time.strftime(GlobalConstants::TIME_FORMATE) %>
      </td>
      <td>
        <%= appointment&.doctor.specialist %>
      </td>
      <td>
        <%= status(appointment) %>
      </td>
    </tr>
  <% end %>
</table>
<%= link_to "Book Appointment", book_appointments_path %><br />